### PR TITLE
License Hygiene

### PR DESCRIPTION
**Pull request by DerekSiemens**
## Description of the change

Update to license and package.json to improve hygiene 

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation or Development tools (readme, specs, tests, code formatting)

## Links

- Jira issue number: (PUT IT HERE)
- Process.st launch checklist: (PUT IT HERE)

### Development

- [ ] [Prettier](https://www.npmjs.com/package/prettier) was run (if applicable)
- [ ] The behaviour changes in the pull request are covered by specs
- [ ] All tests related to the changed code pass in development

### Paperwork

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has a Jira number
- [ ] This pull request has a Process.st launch checklist

### Code review

- [ ] Changes have been reviewed by at least one other engineer
- [ ] Security impacts of this change have been considered

### CODE REVIEW

**Comment by DerekSiemens** [comment]
Oops we can probably close https://github.com/saasquatch/jotai-hook-form/pull/2 when we do this

**Comment by DerekSiemens** [comment]
@Locrian24 I added a changelog here and the version has been bumped to 1.0.0. We should sync about getting a 1.0.0 out, also likely need you to hop in for a bit of general hygiene before that happens

**Review by johanventer — APPROVED** [review]
Ready for package publishing

**Comment by Locrian24** [comment]
This PR has been merged into the v1 release branch

**Pull request closed without merging**
